# Numpy Assignment Questions

In [3]:
import numpy as np

1. What is a Python library? Why do we use Python libraries?

In [1]:
import pandas as pd
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print(df)


    Name  Age
0  Alice   25
1    Bob   30


2. What is the difference between Numpy array and List?

NumPy Array:                                                                    
Data Type:	                Homogeneous: All elements must be of the same data type.	        
Performance:                Faster due to efficient memory handling and vectorized operations.	
Memory Usage:	            Uses less memory because it stores data in contiguous blocks.	    
Functionality:	            Supports advanced mathematical and scientific operations like matrix manipulation and linear algebra.
Element-wise Operations:	Supported directly (e.g., addition, multiplication).	            
Dimensionality:             Can handle multi-dimensional data (e.g., 2D matrices, 3D tensors).
Indexing:	                Supports advanced indexing like slicing, masking, and broadcasting.
Built-in Methods:	        Offers many optimized functions for numerical computations.
Data Type Enforcement:	    Automatically converts elements to a single data type (e.g., mixing integers and floats will convert all to floats).	

Python List:
Data Type:                  Heterogeneous: Elements can have different data types.
Performance:                Slower as it stores elements in a fragmented memory.
Memory Usage:               Uses more memory due to overhead for dynamic typing.
Functionality:              Limited functionality for numerical computations.
Element-wise Operations:    Requires explicit iteration or list comprehensions.
mensionality:               Primarily one-dimensional, though nested lists can simulate multi-dimensional data.
Indexing:		            Limited to basic slicing and nested indexing.
Built-in Methods:	        Fewer built-in methods for mathematical operations.
Data Type Enforcement:	    Allows mixed data types without conversion.

In [1]:
#1. Homogeneous vs. Heterogeneous
#   NumPy Array:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)  # [1 2 3]

lst = [1, "two", 3.0]
print(lst)  # [1, "two", 3.0]

#   Python List:
lst = [1, "two", 3.0]
print(lst)  # [1, "two", 3.0]



[1 2 3]
[1, 'two', 3.0]
[1, 'two', 3.0]


In [3]:
#   2. Element-wise Operations
#   NumPy Array:
arr = np.array([1, 2, 3])
print(arr * 2)
# Python List:
lst = [1, 2, 3]
print([x * 2 for x in lst])

[2 4 6]
[2, 4, 6]


In [2]:
#  Performance Comparison

import numpy as np
import time

# NumPy array
arr = np.arange(1_000_000)
start = time.time()
arr_sum = arr + 1
end = time.time()
print("NumPy time:", end - start)

# Python list
lst = list(range(1_000_000))
start = time.time()
lst_sum = [x + 1 for x in lst]
end = time.time()
print("List time:", end - start)


NumPy time: 0.0049877166748046875
List time: 0.1276562213897705


3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

shape=array.shape

size=array.size

dimension=array.ndim

print("Shape of the array:",shape)

print("Size of the array:",size)

print("Shape of the array:",dimension)

Shape of the array: (3, 4)
Size of the array: 12
Shape of the array: 2


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [5]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

first_row=array[0]

print("First row of the array:", first_row)

First row of the array: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]




In [6]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

Element=array[2,3]

print("The Element of Third row and fourth column of the array:", Element)

The Element of Third row and fourth column of the array: 12


6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

odd_index_element=array[1::2,1::2]

print("Odd-indexed elements from the array:",odd_index_element)

Odd-indexed elements from the array: [[6 8]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [8]:
matrix=np.random.rand(3,3)
print("Random 3x3 matrix with values between 0 and 1:")
print(matrix)

Random 3x3 matrix with values between 0 and 1:
[[0.03871699 0.48769004 0.83017341]
 [0.59692206 0.42874856 0.35058753]
 [0.44338279 0.4883237  0.52978597]]


8. Describe the difference between np.random.rand and np.random.randn?

In [9]:
random_array_uniform=np.random.rand(3,3)

random_array_normal=np.random.randn(3,3)

print("Random array from uniform distribution:")
print(random_array_uniform)

print("\nRandom array from standard normal distribution:")
print(random_array_normal)

Random array from uniform distribution:
[[0.32736499 0.06866648 0.74898123]
 [0.78361257 0.88337763 0.17930043]
 [0.20874158 0.33332835 0.82355314]]

Random array from standard normal distribution:
[[-0.07925038  0.99289171 -0.85015946]
 [-1.20952361  0.91699376 -0.1854356 ]
 [-0.93354741 -0.35561093 -0.34956543]]


9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [10]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

increase_dimension=np.expand_dims(array,axis=0)

print("\nArray with increased dimension:")
print(increase_dimension)


Array with increased dimension:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]




In [11]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

transpose=array.T

print("Transposed array using .T attribute:")
print(transpose)

transpose_np=np.transpose(array)

print("\nTransposed array using np.transpose() function:")
print(transpose_np)


Transposed array using .T attribute:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Transposed array using np.transpose() function:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Perform the following operation using Python:
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide matrix B by A

In [12]:
A=np.array([[1,2,3],[5,6,7],[9,10,11]])
B=np.array([[9,10,11],[1,2,3],[5,6,7],])

Index_wise_multiplication=A*B
print("Index-wise multiplication:")
print(Index_wise_multiplication)

matrix_multiplication=np.dot(A,B)
print("\nMatrix multiplication:")
print(matrix_multiplication)

addition=A+B
print("\nAddition of matrices:")
print(addition)

subtraction=A-B
print("\nSubtraction of matrix B from A:")
print(subtraction)

division = B / A
print("\nDivision of matrix B by A:")
print(division)

Index-wise multiplication:
[[ 9 20 33]
 [ 5 12 21]
 [45 60 77]]

Matrix multiplication:
[[ 26  32  38]
 [ 86 104 122]
 [146 176 206]]

Addition of matrices:
[[10 12 14]
 [ 6  8 10]
 [14 16 18]]

Subtraction of matrix B from A:
[[-8 -8 -8]
 [ 4  4  4]
 [ 4  4  4]]

Division of matrix B by A:
[[9.         5.         3.66666667]
 [0.2        0.33333333 0.42857143]
 [0.55555556 0.6        0.63636364]]


12.  Which function in Numpy can be used to swap the byte order of an array?

In [13]:
array=np.array([1,2,3,4], dtype=np.int32)
array.byteswap(inplace=True)
print("Array with byte order swapped (in-place):")
print(array)

Array with byte order swapped (in-place):
[16777216 33554432 50331648 67108864]


13.  What is the significance of the np.linalg.inv function?

The "np.linalg.inv" function plays a vital role in linear algebra computations and numerical simulations, providing a convenient and efficient way to compute the inverse of square matrices in Python using NumPy.

14. What does the np.reshape function do, and how is it used?

In [7]:
#1. Basic Reshaping
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = np.reshape(arr, (2, 3))
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [6]:
#2. Using -1 for Automatic Dimension Calculation
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = np.reshape(arr, (3, -1))
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
#3. Reshaping a Multi-dimensional Array
arr = np.array([[1, 2], [3, 4], [5, 6]])
flattened = np.reshape(arr, (-1,))
print(flattened)
reshaped = np.reshape(arr, (2, 1, 3))
print(reshaped)

[1 2 3 4 5 6]
[[[1 2 3]]

 [[4 5 6]]]


In [9]:
#4.Reshape and Modify
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = np.reshape(arr, (2, 3))
reshaped[0, 0] = 99
print(arr)


[99  2  3  4  5  6]


In [10]:
#1. Shape Mismatch
np.reshape([1, 2, 3, 4], (3, 2))

ValueError: cannot reshape array of size 4 into shape (3,2)

15. What is broadcasting in Numpy?

Broadcasting is a powerful mechanism in NumPy that allows operations to be performed on arrays of different shapes without explicitly reshaping them. It enables NumPy to treat arrays with mismatched dimensions as compatible for element-wise operations by "stretching" one or both arrays as needed.

In [12]:
#1. Scalar and Array
import numpy as np

arr = np.array([1, 2, 3, 4])
result = arr + 10  
print(result)


[11 12 13 14]


In [11]:
# 2. Two Arrays with Compatible Shapes
a = np.array([[1], [2], [3]])  
b = np.array([10, 20, 30, 40])
result = a + b
print(result)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [13]:
#3. Arrays with Different Dimensions
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  
result = a + b
print(result)



[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [14]:
#Unsupported Broadcasting
a = np.array([1, 2])
b = np.array([[1, 2, 3], [4, 5, 6]])
result = a + b

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

# Sorting and Searching

Problem 1 :

Intersection of Two Sorted Arrays

Write a Python program to find the intersection of two sorted arrays.


Input:

A = [1, 3, 5, 7, 9]

B = [2, 4, 5, 8]

Output:

Intersection: [5]

In [14]:
def find_intersection(A, B):
    intersection=[]
    i=j=0
    while i< len(A) and j<len(B):
        if A[i]<B[j]:
            i+=1
        elif A[i] > B[j]:
            j+=1
        else:
            intersection.append(A[i])
            i += 1
            j += 1
    return intersection
A = [1, 3, 5, 7, 9]
B = [2, 4, 5, 8]
intersection = find_intersection(A, B)
print("Intersection:", intersection)

Intersection: [5]



Problem 2 :

Find the Kth Smallest Element

Write a Python function to find the kth smallest element in an unsorted list.


Input:

[12, 3, 1, 7, 8, 20], k = 3

Output:

The 3rd smallest element is 7

In [15]:
def find_kth_smallest(nums,k):
   
   sorted_nums=sorted(nums)

   return sorted_nums[k-1] if 0<k <=len(sorted_nums) else None

nums=[12, 3, 1, 7, 8, 20]
k=3
kth_smallest=find_kth_smallest(nums,k)

if kth_smallest is not None:
   print(f"The {k}rd smallest element is {kth_smallest}")
else:
    print("Invalid value of k")


The 3rd smallest element is 7


Problem 3 : 


Binary Search in a Rotated Sorted Array

Implement a Python program to perform a binary search on a rotated sorted array.


Input:

[4, 5, 6, 7, 8, 9, 1, 2, 3], 6

Output:

Element 6 found at index 2

In [16]:
def search_rotated_array(arr,target):
    def find_pivot(arr):
        left,right=0,len(arr)-1
        while left<right:
            mid=left+(right-left)//2
            if arr[mid]>arr[left]:
                left=mid+1
            else:
                right=mid
        return left
    def binary_search(arr,left,right,target):
        while left<=right:
            mid=left+(right-left)//2
            if arr[mid]==target:
                left=mid+1
            else:
                right=mid-1
        return -1
    pivot=find_pivot(arr)
    if arr[pivot]==target:
        return pivot
    if pivot==0:
        return binary_search(arr,0,len(arr)-1,target)
    if target>arr[-1]:
        return binary_search(arr,0,pivot-1,target)
    else:
        return binary_search(arr,pivot,len(arr)-1,target)
arr = [4, 5, 6, 7, 8, 9, 1, 2, 3]
target = 6
index=search_rotated_array(arr,target)
if index!=-1:
    print(f"Element {target} found at index {index}")
else:
    print("Element not found")

Element not found


In [17]:
def search_rotated_array(arr, target):
    def find_pivot(arr):
        left, right = 0, len(arr) - 1
        
        while left < right:
            mid = left + (right - left) // 2
            
            if arr[mid] > arr[right]:
                left = mid + 1
            else:
                right = mid
        
        return left
    def binary_search(arr, left, right, target):
        while left <= right:
            mid = left + (right - left) // 2
            if arr[mid] == target:
                return mid
            if arr[mid] < target:
                left = mid + 1
            else:
                right = mid - 1    
        return -1
    pivot = find_pivot(arr)
    if arr[pivot] == target:
        return pivot
    
    if pivot == 0:
        return binary_search(arr, 0, len(arr) - 1, target)
    
    if target > arr[-1]:
        return binary_search(arr, 0, pivot - 1, target)
    else:
        return binary_search(arr, pivot, len(arr) - 1, target)
arr = [4, 5, 6, 7, 8, 9, 1, 2, 3]
target = 6
index = search_rotated_array(arr, target)
if index != -1:
    print(f"Element {target} found at index {index}")
else:
    print("Element not found")


Element 6 found at index 2


Problem 4 : 


Searching in a Matrix

Write a Python program that searches for a given element in a 2D matrix and returns its position


Input:

Matrix = [
    [1, 3, 5],
    [7, 9, 11],
    [13, 15, 17]
    ]

Element = 1
Output:

Element 11 found at position (1, 2)

In [18]:
def search_matrix(matrix, target):
    for i, row in enumerate(matrix):
        for j, element in enumerate(row):
            if element==target:
                return i,j
    return None
matrix=np.array([[1,3,5],[7,9,11],[13,15,17]])
element=11
position=search_matrix(matrix,element)
if position:
    print(f"Element {element} found at position {position}")
else:
    print(f"Element {element} not found in the matrix")

Element 11 found at position (1, 2)


Problem 5 : 


Sorting Strings by Length

Write a Python program that takes a list of strings and sorts them based on their length.


Input:

['apple', 'banana', 'kiwi', 'orange', 'grape']


Output:

['kiwi', 'grape', 'apple', 'banana', 'orange']

In [19]:
import numpy as np
def sort_strings_by_length(strings):
    """
    Sort a list of string basen on their length.
    """
    array = np.array(strings)
    lengths=np.array([len(string) for string in array])
    sorted_indices=np.argsort(lengths)
    sorted_array=array[sorted_indices]
    return sorted_array.tolist()
input_strings=['apple', 'banana', 'kiwi', 'orange', 'grape']
sorted_strings=sort_strings_by_length(input_strings)
print("Sorted strings by length:", sorted_strings)

Sorted strings by length: ['kiwi', 'apple', 'grape', 'banana', 'orange']


Problem 6 : 

Implementing the merge sort ( Will be discussed in the class )

In [20]:
import numpy as np
arr=np.array([13,14,12,10,11,9,7,8,4,3,2,5,6,1])
sorted_arr=np.sort(arr)
print("Sorted array",sorted_arr)

Sorted array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Problem 7 : 

Implementing the quick sort ( will be discussed in the class )

In [21]:
import numpy as np
def quicksort(arr):
    if len(arr)<=1:
        return arr
    pivort= arr[len(arr)//2]
    left=arr[arr<pivort]
    middel=arr[arr==pivort]
    right=arr[arr>pivort]
    return np.concatenate((quicksort(left),middel,quicksort(right)))
arr=np.array([13,14,12,10,11,9,7,8,4,3,2,5,6,1])
sorted_arr=quicksort(arr)
print("Sorted array",sorted_arr)

Sorted array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Problem 8 : 

Implementing the count sort ( will be discussed in the class )

In [22]:
import numpy as np
def count_sort(arr):
    max_val=np.max(arr)
    count=np.zeros(max_val+1,dtype=int)
    for num in arr:
        count[num]+=1
    sorted_arr=[]
    for i in range(max_val +1):
        sorted_arr.extend([i]*count[i])
    return np.array(sorted_arr)
arr=np.array([4, 2, 2, 8, 3, 3, 1])
sorted_arr=count_sort(arr)
print("Sorted array",sorted_arr)

Sorted array [1 2 2 3 3 4 8]


Problem 9 : 


Implement a Python function to find a peak element in an array. A peak element is an element that is greater 
than or equal to its neighbors.


Input:

[1, 3, 20, 4, 1, 0]


Output:

Peak element is 20

In [23]:
import numpy as np
def find_peak(arr):
    """
    Find a peak element in the array.
    """
    arr=np.array(arr)
    peak_indices=np.where((arr[:-1]<=arr[1:]) & (arr[1:]>=arr[:-1]))[0]
    if len(peak_indices)>0:
        peak_index=peak_indices[0]
        return arr[peak_index]
    else:
        return None
input_array=[20,21,22,30,41,0,88]
peak_element=find_peak(input_array)
if peak_element is not None:
    print("Peak element is",peak_element)
else:
    print("No peak element found in the array.")

Peak element is 20


Problem 10 : 


Search in a Nearly Sorted Array


Implement a Python program to perform a binary search in a nearly sorted array. In a nearly sorted array, each 
element is at most k positions away from its sorted position.


Input:

[2, 1, 3, 4, 6, 5, 7], k = 1


Output:

Element 5 found at index 4

In [24]:
import numpy as np
def binary_search_nearly_sorted(arr,target,k):
    """
    Perform a binary search in a nearly sorted array.
    """
    arr=np.array(arr)
    left,right=0,len(arr)-1
    while left<=right:
        mid=left+(right-left)//2
        if arr[mid]==target:
            return mid
        for i in range(max(0, mid-k)), min(len(arr),mid+k+1):
            if arr[i]==target:
                return i
            if arr[mid]<target:
                left=mid+1
            else:
                right=mid-1
    return -1
input_array=[2, 1, 3, 4, 6, 5, 7]
target=5
k=1
result_index= binary_search_nearly_sorted(input_array, target, k)
if result_index!=1:
    print(f"Element {target} found at index {result_index} using numpy")
else:
    print("Element {target} not found in the array.")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()